### PR TITLE
Dynamically updates source codebook href

### LINKED ISSUE #5: Source codebook link does not work until after configuring the module
The "Source codebook" and "Target codebook" depend on project IDs being delivered from the backend on page load, during the initial setup, there is no source project set, breaking the link.

https://github.com/ctsit/search_and_populate_data_from_another_project/blob/master/ExternalModule.php#L12-L15

The Source codebook link could dynamically set the PID from the `target_pid` in the configuration menu.

The `source_codebook` button is set here:
https://github.com/ctsit/search_and_populate_data_from_another_project/blob/802b637fc6fc543904f42ed26fa9611a7f5073d0/js/config_menu.js#L3

### PR DESCRIPTION
**Pull request by mbentz-uf**
Closes #5 

Added event listeners to properly update href on project selection.

### CODE REVIEW

**Comment by ChemiKyle** [comment]
This works and the comment is great. I only have one minor gripe though it doesn't seem to affect any functionality at the moment.

File: js/config_menu.js [hunk 1]
```diff
@@ -11,6 +11,30 @@ $(document).ready(function() {
...
+     * This is because the change event on the select list completes before updating, resulting
+     * in the previous option being available rather than the new option that was selected. By keeping
+     * track of the last hovered Project in the dropdown, the href can be properly updated.
+    **/
+    var setSourceCodebook = function() {
+        // Attach mouseenter event listener to project list options to capture last hovered project
+        $('body').on('mouseenter', 'li.select2-results__option', function(event) {
+            var projectText = $(this).text();
+            lastHoveredProjectID = $('tr[field="target_pid"]').find('option:contains("'+projectText+'")').attr('value');
+        });
```
Comment (ChemiKyle) [inline js/config_menu.js:30]: The lack of specificity here causes this chunk to fire when _any_ select2 item is hovered, including the "Show in this form"  and, more importantly, in any other module configuration menu (albeit this module's config window must be opened first).
